[package]
name = "web-scraper"
version = "0.1.0"
edition = "2021"

[dependencies]
inline_colorization = "0.1.6"
reqwest = "0.12.5"
tokio = { version = "=1.39.2", features = ["full"] }
tokio-macros = "2.4.0"
